GUIDANCE: dict[str, str] = {
    "5.1": "A organização deve definir, aprovar pela direção, publicar, comunicar e tomar conhecimento das políticas de segurança da informação. Convém que sejam revistas em intervalos planejados ou quando mudanças significativas ocorrerem. Devem cobrir tópicos como controle de acesso, segurança física, gestão de ativos, transferência de informações e desenvolvimento seguro.",
    "5.2": "Funções e responsabilidades de segurança devem ser claramente atribuídas e documentadas. Inclui proteção de ativos, execução de processos específicos de segurança, gestão de riscos e aceitação de riscos residuais por proprietários de ativos.",
    "5.3": "Funções conflitantes devem ser separadas (ex: solicitar e aprovar pagamentos, desenvolver e implantar em produção, criar e usar credenciais). Quando segregação for inviável, aplicar controles compensatórios como monitoramento, trilhas de auditoria e supervisão.",
    "5.4": "A direção deve demonstrar liderança visível, prover recursos adequados, comunicar a importância da segurança e cobrar conformidade. Inclui aprovação de políticas, alocação de orçamento e responsabilização por incidentes.",
    "5.5": "Manter contatos formais com órgãos reguladores, autoridades policiais, equipes nacionais de resposta a incidentes (CSIRT) e provedores de serviço, para troca rápida de informação durante incidentes ou para conformidade legal.",
    "5.6": "Participação em fóruns setoriais, ISACs, associações de segurança e comunidades de inteligência de ameaças para aprender com pares, receber alertas precoces e contribuir com experiências.",
    "5.7": "Coletar, analisar e produzir inteligência sobre ameaças relevantes aos ativos da organização. Pode ser estratégica (tendências), tática (TTPs) ou operacional (IOCs). Deve alimentar a gestão de risco e detecção.",
    "5.8": "Integrar requisitos de segurança em todas as fases de qualquer projeto, independentemente do tipo. Avaliação de risco no início, especificação de controles, validação antes da entrega.",
    "5.9": "Inventário atualizado de ativos de informação, processos, software, hardware, redes, instalações e pessoal-chave. Cada ativo com proprietário identificado, classificação e localização.",
    "5.10": "Regras claras para uso aceitável de e-mail, internet, dispositivos, dados e instalações. Treinar o pessoal, exigir aceite formal, definir consequências para violações.",
    "5.11": "Procedimento para recolher equipamentos, credenciais, documentos e propriedade intelectual ao final do vínculo. Checklist de saída integrado ao RH.",
    "5.12": "Esquema de classificação com poucos níveis (ex: Público, Interno, Confidencial, Restrito) baseado em impacto de divulgação não autorizada. Revisar periodicamente.",
    "5.13": "Rotular informações física e logicamente conforme o esquema. Em documentos, e-mails, mídias e metadados. Procedimentos para desclassificação quando aplicável.",
    "5.14": "Acordos formais para transferência (físicos, eletrônicos, verbais), incluindo criptografia em trânsito, autenticação, rastreamento e cadeia de custódia para mídias físicas.",
    "5.15": "Política definindo regras de acesso baseadas em necessidade-de-saber e privilégio-mínimo. Cobertura física e lógica. Aprovação formal, revisão periódica, revogação imediata em desligamento.",
    "5.16": "Ciclo de vida completo: criação, modificação, suspensão, exclusão de identidades. IDs únicos, não-reutilizáveis. Identidades compartilhadas devem ser exceção justificada e auditada.",
    "5.17": "Senhas fortes, MFA quando possível, cofre para credenciais privilegiadas, troca obrigatória em primeiro acesso, proibição de senhas padrão em produção.",
    "5.18": "Provisionamento baseado em papéis (RBAC), aprovação pelo proprietário do ativo, revisão trimestral mínima, ajuste em mudanças de função, revogação imediata em desligamento.",
    "5.19": "Identificar e avaliar riscos antes de contratar fornecedores. Tratar segurança da informação como critério de seleção, não apenas custo e prazo.",
    "5.20": "Contratos devem incluir cláusulas de segurança: confidencialidade, direito de auditoria, notificação de incidentes, conformidade com leis, requisitos de devolução de dados ao final.",
    "5.21": "Visibilidade sobre subcontratados (4ª parte). Exigir mesmos requisitos do fornecedor direto. Avaliar riscos de origem (ex: hardware/software).",
    "5.22": "Reuniões periódicas, revisão de SLAs, auditorias, avaliações de pentests do fornecedor, gestão formal de mudanças que afetem segurança.",
    "5.23": "Critérios de seleção do provedor cloud, modelo de responsabilidade compartilhada documentado, configuração segura (CSPM), plano de saída e portabilidade de dados.",
    "5.24": "Processo formal de incident response: papéis, comunicação interna/externa, classificação por severidade, integração com BCP, retenção de evidências.",
    "5.25": "Critérios objetivos para distinguir evento (qualquer ocorrência) de incidente (com impacto adverso). Triagem ágil para evitar fadiga de alertas.",
    "5.26": "Procedimentos de contenção, erradicação, recuperação e comunicação. Treinamento e exercícios (tabletop, simulados). Lições aprendidas registradas.",
    "5.27": "Pós-mortem sem culpa para cada incidente significativo. Atualizar controles, treinamentos e detecções a partir das causas-raiz identificadas.",
    "5.28": "Coleta com cadeia de custódia, hash de integridade, ferramentas forenses, conformidade com requisitos legais para admissibilidade em ações judiciais.",
    "5.29": "Plano que garanta a segurança da informação durante disrupções (não confundir com BCP). Backups acessíveis, controles de acesso mantidos, evitar workarounds inseguros.",
    "5.30": "Recursos de TIC dimensionados para atender RTO/RPO do negócio. Testes periódicos de failover, restauração de backups e procedimentos manuais.",
    "5.31": "Inventário de requisitos legais (LGPD, Marco Civil, setoriais), regulatórios e contratuais. Análise de impacto antes de mudanças regulatórias.",
    "5.32": "Conformidade de licenças de software, proteção de PI da organização e de terceiros, treinamento sobre uso legal de obras de terceiros.",
    "5.33": "Definir tempos de retenção por tipo de registro (legal, contratual, operacional), proteção contra alteração e exclusão prematura, descarte seguro ao fim do prazo.",
    "5.34": "Aderência à LGPD: bases legais, direitos do titular, ROPA (registro de operações), DPIA quando aplicável, encarregado (DPO), notificação de incidentes à ANPD.",
    "5.35": "Auditoria independente (interna ou externa) do SGSI em intervalos planejados ou após mudanças significativas. Reportar resultados à direção.",
    "5.36": "Verificação rotineira de conformidade de processos, sistemas e pessoas com as políticas. Identificar desvios e tratar como não-conformidades.",
    "5.37": "Procedimentos operacionais escritos e acessíveis para todos os recursos de processamento críticos. Revisar e atualizar com mudanças.",
    "6.1": "Background check proporcional à criticidade do papel: referências, antecedentes criminais, escolaridade. Conformidade com leis trabalhistas e LGPD.",
    "6.2": "Cláusulas em contrato de trabalho ou termo: confidencialidade, devolução de ativos, conformidade com políticas, responsabilidades após o término.",
    "6.3": "Programa contínuo: onboarding, reciclagem anual, simulações de phishing, campanhas temáticas, treinamentos específicos para papéis críticos (devs, admins).",
    "6.4": "Processo disciplinar formal documentado, comunicado e aplicado de forma consistente. Cuidado com aspectos trabalhistas e devido processo.",
    "6.5": "Comunicar e fazer cumprir obrigações que persistem após o desligamento: NDAs, não-competição razoável, devolução de propriedade intelectual.",
    "6.6": "NDAs revisados juridicamente, escopo claro, prazos, exceções (informação pública). Assinatura antes de exposição a informação sensível.",
    "6.7": "Política de home office: dispositivos autorizados, VPN, isolamento de rede doméstica, mesa limpa em casa, proibição de redes públicas sem proteção.",
    "6.8": "Canais claros e acessíveis para reporte (e-mail, formulário, chat). Cultura de no-blame para encorajar denúncias precoces. SLA de resposta.",
    "7.1": "Perímetro físico claro, paredes sólidas, portas com fechaduras, sem brechas. Áreas mais sensíveis com perímetros adicionais (defesa em profundidade).",
    "7.2": "Crachá, biometria, registro de entrada/saída, acompanhamento de visitantes, controle de áreas restritas. Revisão periódica de permissões físicas.",
    "7.3": "Posicionar áreas sensíveis longe de público externo, evitar identificação de salas críticas, controlar entregas em área separada da operacional.",
    "7.4": "CFTV em entradas, sensores de invasão, alarmes integrados ao SOC, retenção de imagens conforme requisitos legais.",
    "7.5": "Proteção contra incêndio, inundação, terremoto, sabotagem. Sistemas de detecção e supressão, redundância de localização para sistemas críticos.",
    "7.6": "Regras específicas para trabalho em áreas seguras: acompanhamento, restrição de dispositivos pessoais, revisão de saída, registro de atividade.",
    "7.7": "Mesa limpa ao sair (papéis, mídias). Tela bloqueada automaticamente após inatividade. Cuidado com impressões deixadas em impressoras compartilhadas.",
    "7.8": "Equipamentos protegidos contra furto, dano e acesso não autorizado. Atenção a posicionamento (visibilidade de telas, exposição a líquidos/calor).",
    "7.9": "Notebooks, tablets, mídias fora do escritório: criptografia em repouso, rastreamento, política de transporte e armazenamento em viagens.",
    "7.10": "Ciclo de vida de mídias (HDs, fitas, USB): registro, criptografia, controle de movimentação, sanitização ou destruição certificada no descarte.",
    "7.11": "Redundância de energia (no-break, gerador), refrigeração, telecomunicações. Testes regulares dos sistemas redundantes.",
    "7.12": "Cabos protegidos contra interceptação (canaletas, conduítes), separação física de cabos de força/dados, identificação clara, proteção contra danos.",
    "7.13": "Manutenção preventiva e corretiva por pessoal autorizado. Equipamentos saindo para manutenção externa devem ter dados removidos ou estar criptografados.",
    "7.14": "Sanitização certificada (wipe, degauss, destruição física) antes de descarte ou reuso. Inclui licenças de software a serem removidas.",
    "8.1": "Endpoint hardening, EDR/antivírus, criptografia de disco, MDM/MAM para mobile, política de BYOD se aplicável, atualizações automáticas.",
    "8.2": "Contas privilegiadas separadas das de uso comum, just-in-time access, PAM (vault), revisão frequente, MFA obrigatório.",
    "8.3": "Acesso por papel/atributo (RBAC/ABAC), princípio do privilégio mínimo, segregação por classificação, revogação automática em mudança de função.",
    "8.4": "Repositórios protegidos, autenticação forte, code review obrigatório, controle de branches, escaneamento de segredos em commits.",
    "8.5": "MFA, SSO, anti-bruteforce (rate limiting, lockout), feedback genérico em erros de login, sessão com timeout.",
    "8.6": "Monitorar CPU, memória, storage, banda. Projeções de crescimento, planejamento de capacidade, alarmes preventivos.",
    "8.7": "EDR moderno (não apenas AV de assinatura), proteção em múltiplas camadas (e-mail, navegação, endpoint), conscientização do usuário.",
    "8.8": "Scanner contínuo, priorização por exploitabilidade e exposição (não apenas CVSS), SLA de patch por criticidade, gestão de exceções.",
    "8.9": "Baselines de configuração (CIS Benchmarks), automação de aplicação (IaC), monitoramento de drift, hardening sistemático.",
    "8.10": "Exclusão segura quando dados deixam de ser necessários: retenção mínima, comando explícito de exclusão, evidência de descarte.",
    "8.11": "Mascaramento, anonimização, pseudonimização em ambientes não-produtivos. Tokenização para dados sensíveis em uso.",
    "8.12": "DLP em endpoint, e-mail e nuvem. Classificação automática, bloqueio/alerta em transferências indevidas, retenção de evidências.",
    "8.13": "Estratégia 3-2-1 (3 cópias, 2 mídias, 1 offsite). Backup imutável contra ransomware. Testes regulares de restauração.",
    "8.14": "Redundância em servidores, storage, redes. Cluster, replicação, failover automatizado. Testes de comutação.",
    "8.15": "Logs de eventos de segurança, acesso, mudanças, erros. Centralização (SIEM), proteção contra alteração, retenção conforme requisitos.",
    "8.16": "Monitoramento contínuo (SOC), correlação de eventos, threat hunting, casos de uso ajustados ao ambiente, métricas (MTTD, MTTR).",
    "8.17": "NTP confiável e redundante. Sem sincronização, logs ficam inconsistentes, dificultando investigação forense.",
    "8.18": "Utilitários que podem burlar controles (debuggers, packet sniffers) devem ser instalados apenas onde necessários, com aprovação e logs.",
    "8.19": "Allowlisting de software, repositórios internos validados, proibição de instalação por usuários comuns, processo formal para novos softwares.",
    "8.20": "Segmentação, firewalls modernos (NGFW), IPS, controle de acesso à rede (NAC), monitoramento de tráfego anômalo.",
    "8.21": "SLA de segurança com provedores de rede, monitoramento de disponibilidade e integridade, criptografia em links externos.",
    "8.22": "Segmentação por função (DMZ, servidores, usuários, OT), microssegmentação onde aplicável, controle de tráfego entre segmentos.",
    "8.23": "Filtro de URL/DNS, bloqueio de categorias de risco, proteção contra phishing, isolamento de navegação para acessos sensíveis.",
    "8.24": "Política de criptografia: algoritmos aprovados (AES-256, TLS 1.2+), gestão de chaves (HSM, KMS), rotação periódica, criptografia em repouso e trânsito.",
    "8.25": "SDLC seguro: requisitos, threat modeling, code review, SAST/DAST, gestão de dependências (SCA), testes de segurança automatizados.",
    "8.26": "Requisitos de segurança formalizados (autenticação, autorização, logging, criptografia), aprovados pelas partes interessadas antes do desenvolvimento.",
    "8.27": "Princípios: defesa em profundidade, fail-secure, privilégio mínimo, redução de superfície de ataque, zero trust onde aplicável.",
    "8.28": "Padrões de codificação segura (OWASP), bibliotecas seguras por default, validação rigorosa de entrada, escape correto em saída.",
    "8.29": "Testes em pipeline CI/CD: SAST, DAST, SCA, IAST. Pentest antes de release. Bug bounty para apps voltadas para internet.",
    "8.30": "Cláusulas de segurança em contratos de desenvolvimento terceirizado, code review pelo time interno, testes de aceitação, proteção da propriedade intelectual.",
    "8.31": "Ambientes separados física ou logicamente, dados de produção não usados em dev/teste sem mascaramento, deploy só com aprovação formal.",
    "8.32": "Change management formal: solicitação, análise de risco, aprovação, testes, plano de rollback, janela de mudança, registro pós-implantação.",
    "8.33": "Dados de teste não devem ser cópia de produção sem tratamento. Quando inevitável, restringir acesso e prazo de uso, descartar após uso.",
    "8.34": "Auditorias coordenadas com a operação, evitar mudanças em horário crítico, acesso somente leitura quando possível, registro detalhado das atividades de auditoria.",
}

assert len(GUIDANCE) == 93, f"GUIDANCE deve cobrir 93 controles, tem {len(GUIDANCE)}"
